services:
  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: dataratz
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dataratz
    ports:
      - "5432:5432"  # host:container
